---
- name: Install Zsh
  ansible.builtin.apt:
    name: zsh
    state: present

- name: Check for /usr/bin/zsh
  ansible.builtin.stat:
    path: /usr/bin/zsh
  register: zsh_usr

- name: Check for /bin/zsh
  ansible.builtin.stat:
    path: /bin/zsh
  register: zsh_bin

- name: Set zsh_path fact
  ansible.builtin.set_fact:
    zsh_path: >-
      {{ '/usr/bin/zsh' if zsh_usr.stat.exists else
         ('/bin/zsh' if zsh_bin.stat.exists else '') }}

- name: Fail if no zsh binary found
  ansible.builtin.fail:
    msg: "zsh binary not found after install"
  when: zsh_path == ''

- name: Ensure Zsh path is present in /etc/shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "{{ zsh_path }}"
    state: present

- name: Set Zsh as default for new user
  ansible.builtin.user:
    name: "{{ new_user }}"
    shell: "{{ zsh_path }}"
  when: new_user is defined

- name: Set Zsh as default for root
  ansible.builtin.user:
    name: root
    shell: "{{ zsh_path }}"

- name: Install Oh My Zsh and Plugins for root and new user
  ansible.builtin.include_tasks: user_zsh_setup.yml
  loop:
    - { user: "root", home: "/root" }
    - { user: "{{ new_user }}", home: "/home/{{ new_user }}" }
