---
- name: Authorize local SSH key for developer
  authorized_key:
    user: "{{ new_user }}"
    state: present
    key: "{{ lookup('file', ssh_key_path) }}"

- name: Deploy hardened sshd_config
  copy:
    src: files/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  notify: Restart SSH
