---
- name: Install Fail2Ban
  apt:
    name: fail2ban
    state: present
    update_cache: true

- name: Initial Fail2Ban setup
  copy:
    src: /etc/fail2ban/jail.conf
    dest: /etc/fail2ban/jail.local
    remote_src: true

- name: Ensure Fail2Ban is started and enabled
  service:
    name: fail2ban
    state: started
    enabled: true
